# Задаём имя проекта
name: htmx-books-dev

services:
  web:
    # Указываем директорию ./app, в которой содержится Dockerfile для сборки образа
    build: .
    # Запускаем встроенный сервер Django
    command: python manage.py runserver 0.0.0.0:8000
    # Файл содержащий переменные окружения для контейнера
    environment:
      - DJANGO_ALLOWED_HOSTS=127.0.0.1
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1
      - CACHES_BACKEND=django.core.cache.backends.memcached.PyMemcacheCache
      - CACHES_LOCATION=memcached:11211
      - INTERNAL_IPS=127.0.0.1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=book_django
      - SQL_USER=book_django
      - SQL_PASSWORD=pass_book_django
      - SQL_HOST=db
      - SQL_PORT=5432
    # Пробрасываем 8000 порт контейнера на 8000 порт локалхоста(127.0.0.1:8000)
    ports:
      - 8000:8000
    depends_on:
      - db
      - memcached

  db:
    # Берём образ БД PostgreSQL версии 15
    image: postgres:16
    # Примонтируем том postgres-data к директории /var/lib/postgresql/data контейнера db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Используем значения переменных окружения из .env файла
    environment:
      - POSTGRES_USER=book_django
      - POSTGRES_PASSWORD=pass_book_django
      - POSTGRES_DB=book_django

  memcached:
    # Берём образ Мemcached версии 1.6.21
    image: memcached:1.6.21

volumes:
  # Объявляем том postgres-data для хранения данных PostgreSQL
  postgres-data: